In [1]:
def open_api():
    
    
#importing libraries
    from requests.exceptions import ConnectionError
    import pandas as pd
    import requests
    import json
    
    
#input of API url
    url = input('enter API URL')
    
    
#try except for checking if the url is valid
    try:
        
#requesting data from API, printing response, reading with json handler, printing the dictornary keys
        r = requests.get(url, timeout=10)
        print(r)
        json = r.json()
        parameters= json.keys()
        print ('The paramters available in API are',  '\n', parameters)
        
#input of which parameter data is to be fetched        
        paramter_open= input('enter parameter to open')
        
#checking if the parameter entered is available in the key or not        
        if paramter_open not in parameters:
            print ('please enter valid parameter from keys')

#converting the data from json to dataframe to be understanable easiely
        else:
            #print(json[key])
            df = pd.DataFrame(json[paramter_open])
            return df
        
    except ConnectionError:
        print ('Failed to open API URL. Please enter correct API URL')

In [2]:
open_api()

enter API URL https://demodev2.kappazeta.ee/ard_api_demo/v1/time_series/s1?limit_to_rasters=true&parcel_foreign_id=1&properties=parcel_foreign_id%2Cs1product_end_time%2Cs1product_ron%2Ccohvh_med%2Ccohvv_med%2Cvhvv_med

<Response [200]>
The paramters available in API are
 dict_keys(['status', 'message', 'parcel_foreign_id', 'page', 'length', 'units', 's1_time_series'])

enter parameter to open s1_time_series

,parcel_foreign_id,s1product_end_time,s1product_ron,cohvh_med,cohvv_med,vhvv_med
0,1,2021-04-29 16:53:11.038489+03,146,0.179159,0.166241,0.198929
1,1,2021-04-30 05:32:53.688369+03,66,0.218344,0.163039,0.196385
2,1,2021-05-01 05:25:13.715124+03,168,0.182925,0.193167,0.199184
3,1,2021-05-04 17:01:21.312047+03,44,0.134668,0.165218,0.230203
4,1,2021-05-05 16:52:31.317421+03,146,0.218076,0.253821,0.242613
...,...,...,...,...,...,...
151,1,2021-12-13 16:53:18.004121+02,146,0.279987,0.352800,0.186539
152,1,2021-12-14 05:33:00.592394+02,66,0.260168,0.330323,0.166774
153,1,2021-12-15 05:25:20.5663+02,168,0.239230,0.304114,0.147779
154,1,2021-12-18 17:01:27.722219+02,44,0.355602,0.416264,0.234173
155,1,2021-12-19 16:52:37.567446+02,146,0.303682,0.333331,0.251533