In [1]:
#importing libraries
import pandas as pd
import requests

In [2]:
#saving API url as variable 
url = 'https://demodev2.kappazeta.ee/ard_api_demo/v1/time_series/s2?limit_to_rasters=true&parcel_foreign_id=1&properties=parcel_foreign_id%2Cs2product_start_time%2Cs2product_ron%2Cndvi_med'

In [3]:
#requesting data to be fetched from url 
r = requests.get(url)

In [4]:
print(r)

<Response [200]>

In [5]:
#reading data from json handler
json = r.json()

In [6]:
#checking dictornary keys in which data is stored
json.keys()

dict_keys(['status', 'message', 'parcel_foreign_id', 'page', 'length', 'units', 's2_time_series'])

In [7]:
json['s2_time_series']

[{'parcel_foreign_id': '1',
  's2product_start_time': '2021-05-09 10:30:21+03',
  's2product_ron': '108',
  'ndvi_med': 0.853386},
 {'parcel_foreign_id': '1',
  's2product_start_time': '2021-05-19 10:30:21+03',
  's2product_ron': '108',
  'ndvi_med': 0.901152},
 {'parcel_foreign_id': '1',
  's2product_start_time': '2021-05-24 10:25:59+03',
  's2product_ron': '108',
  'ndvi_med': 0.919272},
 {'parcel_foreign_id': '1',
  's2product_start_time': '2021-05-31 10:15:59+03',
  's2product_ron': '065',
  'ndvi_med': 0.6148},
 {'parcel_foreign_id': '1',
  's2product_start_time': '2021-06-03 10:25:59+03',
  's2product_ron': '108',
  'ndvi_med': 0.555089},
 {'parcel_foreign_id': '1',
  's2product_start_time': '2021-06-05 10:20:21+03',
  's2product_ron': '065',
  'ndvi_med': 0.564536},
 {'parcel_foreign_id': '1',
  's2product_start_time': '2021-06-08 10:30:21+03',
  's2product_ron': '108',
  'ndvi_med': 0.66744},
 {'parcel_foreign_id': '1',
  's2product_start_time': '2021-06-18 10:30:21+03',
  's2product_ron': '108',
  'ndvi_med': 0.825895},
 {'parcel_foreign_id': '1',
  's2product_start_time': '2021-06-28 10:30:21+03',
  's2product_ron': '108',
  'ndvi_med': 0.862776},
 {'parcel_foreign_id': '1',
  's2product_start_time': '2021-07-15 10:20:31+03',
  's2product_ron': '065',
  'ndvi_med': 0.547564},
 {'parcel_foreign_id': '1',
  's2product_start_time': '2021-08-02 10:25:59+03',
  's2product_ron': '108',
  'ndvi_med': 0.828247},
 {'parcel_foreign_id': '1',
  's2product_start_time': '2021-08-04 10:20:31+03',
  's2product_ron': '065',
  'ndvi_med': 0.85777},
 {'parcel_foreign_id': '1',
  's2product_start_time': '2021-08-12 10:25:59+03',
  's2product_ron': '108',
  'ndvi_med': 0.818261},
 {'parcel_foreign_id': '1',
  's2product_start_time': '2021-08-14 10:20:31+03',
  's2product_ron': '065',
  'ndvi_med': 0.822567},
 {'parcel_foreign_id': '1',
  's2product_start_time': '2021-08-17 10:30:21+03',
  's2product_ron': '108',
  'ndvi_med': 0.841156},
 {'parcel_foreign_id': '1',
  's2product_start_time': '2021-09-01 10:25:59+03',
  's2product_ron': '108',
  'ndvi_med': 0.880666},
 {'parcel_foreign_id': '1',
  's2product_start_time': '2021-09-08 10:15:59+03',
  's2product_ron': '065',
  'ndvi_med': 0.853599},
 {'parcel_foreign_id': '1',
  's2product_start_time': '2021-09-18 10:16:39+03',
  's2product_ron': '065',
  'ndvi_med': 0.729443},
 {'parcel_foreign_id': '1',
  's2product_start_time': '2021-09-26 10:30:31+03',
  's2product_ron': '108',
  'ndvi_med': 0.821583},
 {'parcel_foreign_id': '1',
  's2product_start_time': '2021-10-06 10:29:21+03',
  's2product_ron': '108',
  'ndvi_med': 0.855399},
 {'parcel_foreign_id': '1',
  's2product_start_time': '2021-10-08 10:18:29+03',
  's2product_ron': '065',
  'ndvi_med': 0.916698},
 {'parcel_foreign_id': '1',
  's2product_start_time': '2021-10-11 10:28:49+03',
  's2product_ron': '108',
  'ndvi_med': 0.867542},
 {'parcel_foreign_id': '1',
  's2product_start_time': '2021-10-13 10:19:51+03',
  's2product_ron': '065',
  'ndvi_med': 0.914733},
 {'parcel_foreign_id': '1',
  's2product_start_time': '2021-10-23 10:21:01+03',
  's2product_ron': '065',
  'ndvi_med': 0.888889},
 {'parcel_foreign_id': '1',
  's2product_start_time': '2021-11-10 10:31:49+02',
  's2product_ron': '108',
  'ndvi_med': 0.795467},
 {'parcel_foreign_id': '1',
  's2product_start_time': '2021-11-22 10:23:31+02',
  's2product_ron': '065',
  'ndvi_med': 0.833241}]

In [8]:
#converting data from json to dataframe so it can be understood easily
df = pd.DataFrame(json['s2_time_series'])

In [9]:
df

   parcel_foreign_id    s2product_start_time s2product_ron  ndvi_med
0                  1  2021-05-09 10:30:21+03           108  0.853386
1                  1  2021-05-19 10:30:21+03           108  0.901152
2                  1  2021-05-24 10:25:59+03           108  0.919272
3                  1  2021-05-31 10:15:59+03           065  0.614800
4                  1  2021-06-03 10:25:59+03           108  0.555089
5                  1  2021-06-05 10:20:21+03           065  0.564536
6                  1  2021-06-08 10:30:21+03           108  0.667440
7                  1  2021-06-18 10:30:21+03           108  0.825895
8                  1  2021-06-28 10:30:21+03           108  0.862776
9                  1  2021-07-15 10:20:31+03           065  0.547564
10                 1  2021-08-02 10:25:59+03           108  0.828247
11                 1  2021-08-04 10:20:31+03           065  0.857770
12                 1  2021-08-12 10:25:59+03           108  0.818261
13                 1  2021-08-14 10:20:31+03           065  0.822567
14                 1  2021-08-17 10:30:21+03           108  0.841156
15                 1  2021-09-01 10:25:59+03           108  0.880666
16                 1  2021-09-08 10:15:59+03           065  0.853599
17                 1  2021-09-18 10:16:39+03           065  0.729443
18                 1  2021-09-26 10:30:31+03           108  0.821583
19                 1  2021-10-06 10:29:21+03           108  0.855399
20                 1  2021-10-08 10:18:29+03           065  0.916698
21                 1  2021-10-11 10:28:49+03           108  0.867542
22                 1  2021-10-13 10:19:51+03           065  0.914733
23                 1  2021-10-23 10:21:01+03           065  0.888889
24                 1  2021-11-10 10:31:49+02           108  0.795467
25                 1  2021-11-22 10:23:31+02           065  0.833241